CREATE DATABASE IF NOT EXISTS housingfund_collection
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE housingfund_collection;

DROP TABLE IF EXISTS tb003;
DROP TABLE IF EXISTS tb002;
DROP TABLE IF EXISTS tb001;

CREATE TABLE tb001 (
    SEQNAME VARCHAR(32) PRIMARY KEY COMMENT '键值信息',
    SEQ BIGINT NOT NULL COMMENT '当前序号',
    MAXSEQ BIGINT NOT NULL COMMENT '最大序号',
    SEQ_DESC VARCHAR(200) NOT NULL COMMENT '描述',
    FREEUSE1 VARCHAR(200) NULL COMMENT '备用1',
    CHECK (SEQ > 0),
    CHECK (MAXSEQ > 0),
    CHECK (SEQ <= MAXSEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统参数表';

CREATE TABLE tb002 (
    UNITACCNUM CHAR(12) PRIMARY KEY COMMENT '单位账号',
    UNITNAME VARCHAR(50) NOT NULL COMMENT '单位名称',
    UNITADDR VARCHAR(200) NOT NULL COMMENT '单位地址',
    ORGCODE CHAR(9) NOT NULL COMMENT '组织机构代码',
    UNITKIND CHAR(1) NOT NULL COMMENT '单位类别',
    UNITTYPE CHAR(3) NOT NULL COMMENT '企业类型',
    SALARYDATE CHAR(2) NOT NULL COMMENT '发薪日期',
    PHONE VARCHAR(30) NOT NULL COMMENT '联系电话',
    AGENTNAME VARCHAR(50) NOT NULL COMMENT '单位经办人',
    AGENTIDCARD CHAR(18) NOT NULL COMMENT '经办人身份证号码',
    UNITRATIO DECIMAL(5,3) NOT NULL COMMENT '单位缴存比例',
    PERRATIO DECIMAL(5,3) NOT NULL COMMENT '个人缴存比例',
    REMARK VARCHAR(200) NULL COMMENT '备注',
    ACCSTATE CHAR(1) NOT NULL DEFAULT '0' COMMENT '账户状态：0正常',
    BALANCE DECIMAL(14,2) NOT NULL DEFAULT 0.00 COMMENT '账户余额',
    BASENUMBER DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '缴存基数',
    UNITPAYSUM DECIMAL(14,2) NOT NULL DEFAULT 0.00 COMMENT '单位缴存总额',
    PERPAYSUM DECIMAL(14,2) NOT NULL DEFAULT 0.00 COMMENT '个人缴存总额',
    PERSNUM INT NOT NULL DEFAULT 0 COMMENT '单位人数',
    LASTPAYDATE DATE NOT NULL DEFAULT '1899-12-01' COMMENT '最后缴存日期',
    INSTCODE CHAR(4) NOT NULL DEFAULT '0110' COMMENT '机构代码',
    OP CHAR(6) NOT NULL DEFAULT '111111' COMMENT '操作员',
    CREATDATE DATE NOT NULL COMMENT '开户日期',
    UNIQUE KEY uk_tb002_orgcode_accstate (ORGCODE, ACCSTATE),
    KEY idx_tb002_unitname (UNITNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='单位基本资料表';

CREATE TABLE tb003 (
    PERACCNUM CHAR(12) PRIMARY KEY COMMENT '个人账号',
    UNITACCNUM CHAR(12) NOT NULL COMMENT '所属单位账号',
    PERNAME VARCHAR(50) NOT NULL COMMENT '个人姓名',
    IDTYPE VARCHAR(20) NOT NULL DEFAULT '01身份证' COMMENT '证件类型',
    IDCARD VARCHAR(30) NOT NULL COMMENT '证件号码',
    PHONE VARCHAR(30) NULL COMMENT '联系电话',
    ADDRESS VARCHAR(200) NULL COMMENT '联系地址',
    BASENUM DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '缴存基数',
    UNITRATIO DECIMAL(5,3) NOT NULL DEFAULT 0.000 COMMENT '单位缴存比例',
    PERRATIO DECIMAL(5,3) NOT NULL DEFAULT 0.000 COMMENT '个人缴存比例',
    UNITMONTHPAY DECIMAL(14,2) NOT NULL DEFAULT 0.00 COMMENT '单位月缴额',
    PERMONTHPAY DECIMAL(14,2) NOT NULL DEFAULT 0.00 COMMENT '个人月缴额',
    PERBALANCE DECIMAL(14,2) NOT NULL DEFAULT 0.00 COMMENT '个人账户余额',
    STATUS CHAR(1) NOT NULL DEFAULT '0' COMMENT '状态：0正常，9销户',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_tb003_idcard (IDCARD),
    KEY idx_tb003_unitaccnum (UNITACCNUM),
    CONSTRAINT fk_tb003_unitaccnum FOREIGN KEY (UNITACCNUM) REFERENCES tb002 (UNITACCNUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='个人基本资料表';
