SET NAMES utf8mb4;

CREATE DATABASE IF NOT EXISTS housingfund_collection
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE housingfund_collection;

DROP TABLE IF EXISTS TB003;
DROP TABLE IF EXISTS TB002;
DROP TABLE IF EXISTS TB001;

CREATE TABLE TB001 (
    SEQNAME CHAR(20) PRIMARY KEY COMMENT '键值信息',
    SEQ BIGINT NOT NULL COMMENT '当前序号',
    MAXSEQ BIGINT NOT NULL COMMENT '最大序号',
    `DESC` VARCHAR(200) NOT NULL COMMENT '描述',
    FREEUSE1 VARCHAR(200) NULL COMMENT '备用1',
    CHECK (SEQ > 0),
    CHECK (MAXSEQ > 0),
    CHECK (SEQ <= MAXSEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统参数表';

CREATE TABLE TB002 (
    UNITACCNUM CHAR(12) PRIMARY KEY COMMENT '单位公积金账号',
    UNITACCNAME VARCHAR(50) NOT NULL COMMENT '单位名称',
    UNITADDR VARCHAR(200) NOT NULL COMMENT '单位地址',
    ORGCODE CHAR(20) NOT NULL COMMENT '组织机构代码',
    UNITCHAR CHAR(1) NOT NULL COMMENT '单位类别',
    UNITKIND CHAR(3) NOT NULL COMMENT '企业类型',
    SALARYDATE CHAR(2) NOT NULL COMMENT '发薪日期',
    UNITPHONE VARCHAR(30) NOT NULL COMMENT '联系电话',
    UNITLINKMAN VARCHAR(50) NOT NULL COMMENT '单位经办人',
    UNITAGENTPAPNO CHAR(18) NOT NULL COMMENT '经办人身份证号码',
    ACCSTATE CHAR(1) NOT NULL DEFAULT '0' COMMENT '账户状态：0正常',
    BALANCE DECIMAL(16,2) NOT NULL DEFAULT 0.00 COMMENT '公积金余额',
    BASENUMBER DECIMAL(16,2) NOT NULL DEFAULT 0.00 COMMENT '缴存基数',
    UNITPROP DECIMAL(5,3) NOT NULL COMMENT '单位比例',
    PERPROP DECIMAL(5,3) NOT NULL COMMENT '个人比例',
    UNITPAYSUM DECIMAL(16,2) NOT NULL DEFAULT 0.00 COMMENT '单位月应缴额',
    PERPAYSUM DECIMAL(16,2) NOT NULL DEFAULT 0.00 COMMENT '个人月应缴额',
    PERSNUM INT NOT NULL DEFAULT 0 COMMENT '单位人数',
    LASTPAYDATE DATE NOT NULL DEFAULT '1899-12-01' COMMENT '最后汇缴月',
    INSTCODE CHAR(8) NOT NULL DEFAULT '0110' COMMENT '公积金中心机构代码',
    OP CHAR(6) NOT NULL DEFAULT '111111' COMMENT '柜员',
    CREATDATE DATE NOT NULL COMMENT '建立日期',
    REMARK VARCHAR(200) NULL COMMENT '备注',
    UNIQUE KEY uk_tb002_orgcode_accstate (ORGCODE, ACCSTATE),
    KEY idx_tb002_unitaccname (UNITACCNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='单位基本资料表';

CREATE TABLE TB003 (
    ACCNUM CHAR(12) PRIMARY KEY COMMENT '个人公积金账号',
    UNITACCNUM CHAR(12) NOT NULL COMMENT '单位公积金账号',
    PERNAME VARCHAR(12) NOT NULL COMMENT '姓名',
    IDTYPE VARCHAR(20) NOT NULL DEFAULT '01身份证' COMMENT '证件类型',
    IDCARD VARCHAR(30) NOT NULL COMMENT '证件号码',
    OPENDATE DATE NOT NULL COMMENT '开户日期',
    BALANCE DECIMAL(16,2) NOT NULL DEFAULT 0.00 COMMENT '公积金余额',
    PERACCSTATE CHAR(1) NOT NULL DEFAULT '0' COMMENT '个人账户状态：0正常，9销户',
    BASENUMBER DECIMAL(16,2) NOT NULL DEFAULT 0.00 COMMENT '缴存基数',
    UNITPROP DECIMAL(5,3) NOT NULL DEFAULT 0.000 COMMENT '单位比例',
    INDIPROP DECIMAL(5,3) NOT NULL DEFAULT 0.000 COMMENT '个人比例',
    LASTPAYDATE DATE NOT NULL DEFAULT '1899-12-01' COMMENT '最后汇缴月',
    UNITMONPAYSUM DECIMAL(16,2) NOT NULL DEFAULT 0.00 COMMENT '单位月应缴额',
    PERMONPAYSUM DECIMAL(16,2) NOT NULL DEFAULT 0.00 COMMENT '个人月应缴额',
    YPAYAMT DECIMAL(16,2) NOT NULL DEFAULT 0.00 COMMENT '本年汇补缴额',
    YDRAWAMT DECIMAL(16,2) NOT NULL DEFAULT 0.00 COMMENT '年提取额',
    YINTERESTBAL DECIMAL(16,2) NOT NULL DEFAULT 0.00 COMMENT '年度结息',
    INSTCODE CHAR(8) NOT NULL DEFAULT '0110' COMMENT '公积金中心机构代码',
    OP CHAR(6) NOT NULL DEFAULT '111111' COMMENT '柜员',
    REMARK VARCHAR(200) NULL COMMENT '备注',
    UNIQUE KEY uk_tb003_idcard (IDCARD),
    KEY idx_tb003_unitaccnum (UNITACCNUM),
    CONSTRAINT fk_tb003_unitaccnum FOREIGN KEY (UNITACCNUM) REFERENCES TB002 (UNITACCNUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='个人基本资料表';
